
----- DROPS ------

DROP INDEX IDX_GLPI_TICKET;
DROP INDEX IDX_GLPI_TICKET_TASK;
DROP INDEX IDX_GLPI_TICKET_SOLUTION;
DROP INDEX IDX_GLPI_NOTIFICATION;
DROP INDEX GLPI_CLUSTER_IDX;

-------------- INDEXES --------------

CREATE INDEX IDX_GLPI_TICKET
    ON GLPI_TICKET (ID, OWNER_ID, OPERATOR_ID);

CREATE INDEX IDX_GLPI_TICKET_TASK
    ON GLPI_TICKET_TASK (ID, TICKET_ID);

CREATE INDEX IDX_GLPI_TICKET_SOLUTION
    ON GLPI_TICKET_SOLUTION (ID, TICKET_ID);

CREATE INDEX IDX_GLPI_NOTIFICATION
    ON GLPI_NOTIFICATION (ID, USER_ID, OPERATOR_ID, TICKET_ID);

CREATE INDEX GLPI_CLUSTER_USER_IDX
    ON CLUSTER GLPI_CLUSTER_USER;

CREATE INDEX GLPI_CLUSTER_TICKET_IDX
    ON CLUSTER GLPI_CLUSTER_TICKET;
