ALTER SESSION SET "_ORACLE_SCRIPT"=true; 

----------- DROPS -----------

DROP ROLE ROLE_ADMIN;
DROP ROLE ROLE_USER;
DROP ROLE ROLE_OPERATOR;

----------- ROLES -----------

-- Role admin
CREATE ROLE ROLE_ADMIN;

GRANT CONNECT TO ROLE_ADMIN;

GRANT SELECT, INSERT, UPDATE ON GLPI_USER TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON GLPI_TICKET TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON GLPI_TICKET_TASK TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON GLPI_TICKET_SOLUTION TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON GLPI_INVENTORY TO ROLE_ADMIN;

GRANT SELECT ON GLPI_NOTIFICATION TO ROLE_ADMIN;

-- Role user
CREATE ROLE ROLE_USER;

GRANT CONNECT TO ROLE_USER;

GRANT SELECT, INSERT ON VIEW_GLPI_TICKET TO ROLE_USER;

GRANT SELECT ON GLPI_NOTIFICATION TO ROLE_USER;
GRANT SELECT, UPDATE ON GLPI_TICKET_SOLUTION TO ROLE_USER;

-- Role Operator
CREATE ROLE ROLE_OPERATOR;

GRANT CONNECT TO ROLE_OPERATOR;

GRANT SELECT, INSERT, UPDATE ON GLPI_TICKET TO ROLE_OPERATOR;
GRANT SELECT, INSERT, UPDATE ON GLPI_TICKET_TASK TO ROLE_OPERATOR;
GRANT SELECT, INSERT, UPDATE ON GLPI_INVENTORY TO ROLE_OPERATOR

GRANT SELECT, INSERT ON GLPI_TICKET_SOLUTION TO ROLE_OPERATOR;

GRANT UPDATE ON VIEW_GLPI_TICKET TO ROLE_OPERATOR;
