-------------- DROPS --------------

DROP CLUSTER GLPI_CLUSTER_USER CASCADE;
DROP CLUSTER GLPI_CLUSTER_TICKET CASCADE;
DROP TABLE GLPI_INVENTORY CASCADE CONSTRAINTS;
DROP TABLE GLPI_USER CASCADE CONSTRAINTS;
DROP TABLE GLPI_TICKET CASCADE CONSTRAINTS;
DROP TABLE GLPI_TICKET_TASK CASCADE CONSTRAINTS;
DROP TABLE GLPI_TICKET_SOLUTION CASCADE CONSTRAINTS;
DROP TABLE GLPI_NOTIFICATION CASCADE CONSTRAINTS;

-------------- CLUSTERS --------------

CREATE CLUSTER GLPI_CLUSTER_USER (ID VARCHAR2(16))
TABLESPACE GLPI
STORAGE (INITIAL 10K NEXT 50K);

CREATE CLUSTER GLPI_CLUSTER_TICKET (TICKET_ID VARCHAR2(16))
TABLESPACE GLPI
STORAGE (INITIAL 10K NEXT 50K);

-------------- TABLES --------------

CREATE TABLE GLPI_USER
(
    ID           VARCHAR2(16) not null,
    NAME         VARCHAR2(50) not null,
    EMAIL        VARCHAR2(50) not null,
    ROLE         VARCHAR2(16) not null,
    CONSTRAINT GLPI_USER_PK
        PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_EMAIL unique (EMAIL),
    CONSTRAINT ROLE_ENUM
        CHECK (role in ('Operator', 'User'))
) CLUSTER GLPI_CLUSTER_USER (ID);

CREATE TABLE GLPI_INVENTORY
(
    ID        VARCHAR2(16)  not null,
    CATEGORY  VARCHAR2(16)  not null,
    REFERENCE VARCHAR2(100) not null,
    OWNER_ID     VARCHAR2(16) not null,
    CONSTRAINT GLPI_INVENTORY_PK
        PRIMARY KEY (ID),
    CONSTRAINT GLPI_INVENTORY_GLPI_OWNER_ID_FK
        FOREIGN KEY (OWNER_ID) REFERENCES GLPI_USER(ID),
    CONSTRAINT GLPI_INVENTORY_CATEGORY_ENUM
        CHECK (category in ('Software', 'Hardware', 'Network', 'Others'))
) CLUSTER GLPI_CLUSTER_USER (OWNER_ID);

CREATE TABLE GLPI_TICKET
(
    ID           VARCHAR2(16) not null,
    TYPE         VARCHAR2(16) not null,
    CATEGORY     VARCHAR2(16) not null,
    IMPACT       VARCHAR2(16) not null,
    URGENCY      VARCHAR2(16) not null,
    PRIORITY     VARCHAR2(16) not null,
    STATUS       VARCHAR2(16) not null,
    TITLE        VARCHAR2(100) not null,
    DESCRIPTION  VARCHAR2(4000),
    DATE_CREATED DATE DEFAULT SYSDATE,
    DATE_UPDATED DATE DEFAULT SYSDATE,
    DATE_CLOSED  DATE,
    OWNER_ID     VARCHAR2(16) not null,
    OPERATOR_ID  VARCHAR2(16),
    INVENTORY_ITEM_ID     VARCHAR2(16) not null,
    CONSTRAINT TABLE_NAME_PK
        PRIMARY KEY (ID),
    CONSTRAINT GLPI_TICKET_GLPI_USER_ID_FK
        FOREIGN KEY (OPERATOR_ID) REFERENCES GLPI_USER,
    CONSTRAINT GLPI_TICKET_GLPI_USER_ID_FK_2
        FOREIGN KEY (OWNER_ID) REFERENCES GLPI_USER,
    CONSTRAINT GLPI_TICKET_GLPI_USER_ID_FK_3
        FOREIGN KEY (INVENTORY_ITEM_ID) REFERENCES GLPI_INVENTORY,
    CONSTRAINT CATEGORY_ENUM
        CHECK (category in ('Software', 'Hardware', 'Network', 'Others')),
    CONSTRAINT IMPACT_ENUM
        CHECK (impact in ('Low', 'Medium', 'High')),
    CONSTRAINT PRIORITY_ENUM
        CHECK (priority in ('Low', 'Medium', 'High')),
    CONSTRAINT STATUS_ENUM
        CHECK (status in ('Waiting', 'Attributed', 'Resolved', 'Closed', 'Deleted')),
    CONSTRAINT TYPE_ENUM
        CHECK (type in ('Incident', 'Request')),
    CONSTRAINT URGENCY_ENUM
        CHECK (urgency in ('Low', 'Medium', 'High'))
) CLUSTER GLPI_CLUSTER_TICKET (ID);


CREATE TABLE GLPI_TICKET_TASK
(
    ID           VARCHAR2(16) not null,
    TICKET_ID    VARCHAR2(16) not null,
    DATE_CREATED DATE DEFAULT SYSDATE,
    DESCRIPTION  VARCHAR2(500),
    CONSTRAINT GLPI_TICKET_TASK_PK
        PRIMARY KEY (ID),
    CONSTRAINT GLPI_TICKET_TASK_TICKET_ID_FK
        FOREIGN KEY (TICKET_ID) REFERENCES GLPI_TICKET
) CLUSTER GLPI_CLUSTER_TICKET (TICKET_ID);


CREATE TABLE GLPI_TICKET_SOLUTION
(
    ID           VARCHAR2(16) not null,
    TICKET_ID    VARCHAR2(16) not null,
    DATE_CREATED DATE DEFAULT SYSDATE,
    DESCRIPTION  VARCHAR2(500),
    APPROVAL     NUMBER(1) default 0,
    CONSTRAINT GLPI_TICKET_SOLUTION_PK
        PRIMARY KEY (ID),
    CONSTRAINT GLPI_TICKET_SOLUTION_TICKET_ID_FK
        FOREIGN KEY (TICKET_ID) REFERENCES GLPI_TICKET,
    CONSTRAINT APPROVAL_BOOLEAN
        CHECK (approval in (0, 1))
) CLUSTER GLPI_CLUSTER_TICKET (TICKET_ID);


CREATE TABLE GLPI_NOTIFICATION
(
    ID          VARCHAR2(16) not null, -- ID de la notification
    USER_ID     VARCHAR2(16) NOT NULL, -- ID de l'utilisateur
    OPERATOR_ID VARCHAR2(16), -- ID de l'opérateur
    TICKET_ID   VARCHAR2(16) NOT NULL, -- ID du ticket
    MESSAGE     VARCHAR2(255) not null, -- Message de la notification
    DATE_CREATED DATE DEFAULT SYSDATE, -- Date de création de la notification
    STATUS      VARCHAR2(20) DEFAULT 'Attente', -- Valeurs : 'Attente', 'traitée', 'échouée'
    CONSTRAINT FK_GLPI_NOTIFICATION_USER_ID
        FOREIGN KEY (USER_ID) REFERENCES GLPI_USER(ID), -- Clé étrangère vers la table GLPI_USER
    CONSTRAINT FK_GLPI_NOTIFICATION_OPERATOR_ID 
        FOREIGN KEY (OPERATOR_ID) REFERENCES GLPI_USER(ID), -- Clé étrangère vers la table GLPI_USER
    CONSTRAINT FK_GLPI_NOTIFICATION_TICKET_ID
        FOREIGN KEY (TICKET_ID) REFERENCES GLPI_TICKET(ID) -- Clé étrangère vers la table GLPI_TICKET
) CLUSTER GLPI_CLUSTER_TICKET (TICKET_ID);



